# Generated by Django 3.2.5 on 2021-10-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_code_from', models.CharField(max_length=100)),
                ('currency_name_from', models.CharField(max_length=100)),
                ('currency_code_to', models.CharField(max_length=100)),
                ('currency_name_to', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('last_refreshed', models.DateTimeField(auto_now_add=True)),
                ('time_zone', models.CharField(max_length=50)),
                ('bid_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ask_price', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
